#!/usr/bin/env bash
#
#
#
#
#
#

echo $$ >> /var/run/myscript.pid
file="/var/run/myscript.pid"
trap 'echo "I hate the kill command";rm "$file";exit' SIGTERM SIGQUIT
trap 'echo "Y U no love me"' SIGINT
while true
do
	echo "To infinity and beyond"
	sleep 1
done

